---

Logic Modules:
  - module: &schema
      name: schema

  - module: &import
      name: import
      dependencies: [schema]

  - module: &symbol-lookup
      name: symbol-lookup
      dependencies: [schema]

  - module: &callgraph
      name: callgraph
      dependencies: [schema, symbol-lookup]

  - module: &points-to
      name: points-to
      dependencies: [schema, symbol-lookup, callgraph]


Analysis Steps:
  - step: *schema
  - step: *import
  - step: *symbol-lookup
  - step: *callgraph
  - step: *points-to


Statistics:
  Predicate Counts:
    - predicate: "instruction"
      project: *schema

    - predicate: "reachable_function"
      project: *callgraph

    - predicate: "callgraph:edge"
      project: *callgraph

    - predicate: "var_points_to"
      project: *points-to
      header: var-points-to
